player_manager.AddValidModel( "PGAC V2 Soldier 1", "models/csleader/paapmc/player/pgac_soldier_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Soldier 2", "models/csleader/paapmc/player/pgac_soldier2_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Soldier 3", "models/csleader/paapmc/player/pgac_soldier3_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Soldier 4", "models/csleader/paapmc/player/pgac_soldier4_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Soldier 5", "models/csleader/paapmc/player/pgac_soldier5_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Soldier 6", "models/csleader/paapmc/player/pgac_soldier6_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Desert 1", "models/csleader/paapmc/player/pgac_def_soldier_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Desert 2", "models/csleader/paapmc/player/pgac_def_soldier2_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Desert 3", "models/csleader/paapmc/player/pgac_def_soldier3_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Desert 4", "models/csleader/paapmc/player/pgac_def_soldier4_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Desert 5", "models/csleader/paapmc/player/pgac_def_soldier5_pm.mdl" )
player_manager.AddValidModel( "PGAC V2 Desert 6", "models/csleader/paapmc/player/pgac_def_soldier6_pm.mdl" )
player_manager.AddValidHands( "PGAC V2 Soldier 1", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Soldier 2", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Soldier 3", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Soldier 4", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Soldier 5", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Soldier 6", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Desert 1", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Desert 2", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Desert 3", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Desert 4", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Desert 5", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )
player_manager.AddValidHands( "PGAC V2 Desert 6", "models/weapons/c_arms_cstrike.mdl", 0, "00000000" )