CustomizableWeaponry:addFireSound("Weapon_Saiga12.Single", "weapons/saiga12k/12k_fire.wav", 1, 100, CHAN_STATIC)
CustomizableWeaponry:addFireSound("Weapon_Saiga12.Silenced2", "weapons/saiga12k/silenced4.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("saiga.magout", "weapons/saiga12k/12k_magout.wav")
CustomizableWeaponry:addReloadSound("saiga.magin", "weapons/saiga12k/12k_magin.wav")
CustomizableWeaponry:addReloadSound("saiga.magdraw", "weapons/saiga12k/12k_magdraw.wav")
CustomizableWeaponry:addReloadSound("saiga.handle", "weapons/saiga12k/12k_handle.wav")
CustomizableWeaponry:addReloadSound("saiga.click", "weapons/saiga12k/12k_click.wav")
CustomizableWeaponry:addReloadSound("saiga.boltback", "weapons/saiga12k/12k_boltback.wav")
CustomizableWeaponry:addReloadSound("saiga.boltpull", "weapons/saiga12k/12k_boltpull.wav")
CustomizableWeaponry:addReloadSound("saiga.boltforward", "weapons/saiga12k/12k_boltforward.wav")